Fix compilation error on Fedora 35
Error message:

	error: failed to run custom build command for `solana-storage-proto v1.11.7 (/builddir/build/BUILD/solana-1.11.7/storage-proto)`

	Caused by:
	  process didn't exit successfully: `/builddir/build/BUILD/solana-1.11.7/target/release/build/solana-storage-proto-ebd49e0c80c2fbc6/build-script-build` (exit status: 1)
	  --- stdout
	  cargo::rerun-if-changed=proto/confirmed_block.proto
	  cargo::rerun-if-changed=proto/transaction_by_addr.proto
	  cargo:rerun-if-changed=proto/confirmed_block.proto
	  cargo:rerun-if-changed=proto/transaction_by_addr.proto
	  cargo:rerun-if-changed=proto
	  Running: "/usr/bin/protoc" "--include_imports" "--include_source_info" "-o" "/tmp/prost-buildKMluTA/prost-descriptor-set" "-I" "proto" "-I" "/usr/include" "proto/confirmed_block.proto" "proto/transaction_by_addr.proto"

	  --- stderr
	  Error: Custom { kind: Other, error: "protoc failed: confirmed_block.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }